import type { TConstructorIngredient } from '../types';

export const constructorIngredients: TConstructorIngredient[] = [
  {
    _id: '60666c42cc7b410027a1a9b1',
    instanceId: crypto.randomUUID(),
    name: 'Краторная булка N-200i',
    type: 'bun',
    price: 1255,
    image: 'https://code.s3.yandex.net/react/code/bun-02.png',
  },
  {
    _id: '60666c42cc7b410027a1a9b5',
    instanceId: crypto.randomUUID(),
    name: 'Говяжий метеорит (отбивная)',
    type: 'main',
    price: 3000,
    image: 'https://code.s3.yandex.net/react/code/meat-04.png',
  },
  {
    _id: '60666c42cc7b410027a1a9b9',
    instanceId: crypto.randomUUID(),
    name: 'Соус традиционный галактический',
    type: 'sauce',
    price: 15,
    image: 'https://code.s3.yandex.net/react/code/sauce-03.png',
  },
  {
    _id: '60666c42cc7b410027a1a9b4',
    instanceId: crypto.randomUUID(),
    name: 'Мясо бессмертных моллюсков Protostomia',
    type: 'main',
    price: 1337,
    image: 'https://code.s3.yandex.net/react/code/meat-02.png',
  },
  {
    _id: '60666c42cc7b410027a1a9bc',
    instanceId: crypto.randomUUID(),
    name: 'Плоды Фалленианского дерева',
    type: 'main',
    price: 874,
    image: 'https://code.s3.yandex.net/react/code/sp_1.png',
  },
  {
    _id: '60666c42cc7b410027a1a9bb',
    instanceId: crypto.randomUUID(),
    name: 'Хрустящие минеральные кольца',
    type: 'main',
    price: 300,
    image: 'https://code.s3.yandex.net/react/code/mineral_rings.png',
  },
  {
    _id: '60666c42cc7b410027a1a9bb',
    instanceId: crypto.randomUUID(),
    name: 'Хрустящие минеральные кольца',
    type: 'main',
    price: 300,
    image: 'https://code.s3.yandex.net/react/code/mineral_rings.png',
  },
  {
    _id: '60666c42cc7b410027a1a9bd',
    instanceId: crypto.randomUUID(),
    name: 'Кристаллы марсианских альфа-сахаридов',
    type: 'main',
    price: 762,
    image: 'https://code.s3.yandex.net/react/code/core.png',
  },
];
